#!/usr/bin/env python

# command-line interface to ttviewer.py

__author__ = 'Jan Feitsma'

# own imports
import ttvlib


if __name__ == '__main__':
    parser = ttvlib.ttviewer.make_parser()
    parser.add_argument('filenames', help='input file(s)', nargs='+', metavar='filename')
    ttvlib.ttviewer.run(**vars(parser.parse_args()))

